/* 
 * Thermonuclear War REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWarheadsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get the current nuclear warhead status.
        /// </summary>
        /// <remarks>
        /// This method can be used to check the current online status.              Sometimes the wi-fi can be shaky - especially when the microwave is being used.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>WarheadStatusResult</returns>
        WarheadStatusResult WarheadsGetStatus ();

        /// <summary>
        /// Get the current nuclear warhead status.
        /// </summary>
        /// <remarks>
        /// This method can be used to check the current online status.              Sometimes the wi-fi can be shaky - especially when the microwave is being used.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of WarheadStatusResult</returns>
        ApiResponse<WarheadStatusResult> WarheadsGetStatusWithHttpInfo ();
        /// <summary>
        /// Launch the nuclear warheads.
        /// </summary>
        /// <remarks>
        /// The launch code changes every day and is in the format YYMMDD-AAAAAAAAAA (where YYMMDD is 6 digits representing the current              date and AAAAAAAAAA is the pass phrase given to the President). May return an error if somethings are not quite right.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="launchCode">The launch code. See the implementation notes.</param>
        /// <returns>WarheadLaunchResult</returns>
        WarheadLaunchResult WarheadsLaunch (string launchCode);

        /// <summary>
        /// Launch the nuclear warheads.
        /// </summary>
        /// <remarks>
        /// The launch code changes every day and is in the format YYMMDD-AAAAAAAAAA (where YYMMDD is 6 digits representing the current              date and AAAAAAAAAA is the pass phrase given to the President). May return an error if somethings are not quite right.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="launchCode">The launch code. See the implementation notes.</param>
        /// <returns>ApiResponse of WarheadLaunchResult</returns>
        ApiResponse<WarheadLaunchResult> WarheadsLaunchWithHttpInfo (string launchCode);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get the current nuclear warhead status.
        /// </summary>
        /// <remarks>
        /// This method can be used to check the current online status.              Sometimes the wi-fi can be shaky - especially when the microwave is being used.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of WarheadStatusResult</returns>
        System.Threading.Tasks.Task<WarheadStatusResult> WarheadsGetStatusAsync ();

        /// <summary>
        /// Get the current nuclear warhead status.
        /// </summary>
        /// <remarks>
        /// This method can be used to check the current online status.              Sometimes the wi-fi can be shaky - especially when the microwave is being used.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (WarheadStatusResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<WarheadStatusResult>> WarheadsGetStatusAsyncWithHttpInfo ();
        /// <summary>
        /// Launch the nuclear warheads.
        /// </summary>
        /// <remarks>
        /// The launch code changes every day and is in the format YYMMDD-AAAAAAAAAA (where YYMMDD is 6 digits representing the current              date and AAAAAAAAAA is the pass phrase given to the President). May return an error if somethings are not quite right.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="launchCode">The launch code. See the implementation notes.</param>
        /// <returns>Task of WarheadLaunchResult</returns>
        System.Threading.Tasks.Task<WarheadLaunchResult> WarheadsLaunchAsync (string launchCode);

        /// <summary>
        /// Launch the nuclear warheads.
        /// </summary>
        /// <remarks>
        /// The launch code changes every day and is in the format YYMMDD-AAAAAAAAAA (where YYMMDD is 6 digits representing the current              date and AAAAAAAAAA is the pass phrase given to the President). May return an error if somethings are not quite right.
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="launchCode">The launch code. See the implementation notes.</param>
        /// <returns>Task of ApiResponse (WarheadLaunchResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<WarheadLaunchResult>> WarheadsLaunchAsyncWithHttpInfo (string launchCode);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WarheadsApi : IWarheadsApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WarheadsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WarheadsApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WarheadsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public WarheadsApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get the current nuclear warhead status. This method can be used to check the current online status.              Sometimes the wi-fi can be shaky - especially when the microwave is being used.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>WarheadStatusResult</returns>
        public WarheadStatusResult WarheadsGetStatus ()
        {
             ApiResponse<WarheadStatusResult> localVarResponse = WarheadsGetStatusWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the current nuclear warhead status. This method can be used to check the current online status.              Sometimes the wi-fi can be shaky - especially when the microwave is being used.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of WarheadStatusResult</returns>
        public ApiResponse< WarheadStatusResult > WarheadsGetStatusWithHttpInfo ()
        {

            var localVarPath = "/api/warheads/status";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WarheadsGetStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<WarheadStatusResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (WarheadStatusResult) Configuration.ApiClient.Deserialize(localVarResponse, typeof(WarheadStatusResult)));
            
        }

        /// <summary>
        /// Get the current nuclear warhead status. This method can be used to check the current online status.              Sometimes the wi-fi can be shaky - especially when the microwave is being used.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of WarheadStatusResult</returns>
        public async System.Threading.Tasks.Task<WarheadStatusResult> WarheadsGetStatusAsync ()
        {
             ApiResponse<WarheadStatusResult> localVarResponse = await WarheadsGetStatusAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the current nuclear warhead status. This method can be used to check the current online status.              Sometimes the wi-fi can be shaky - especially when the microwave is being used.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (WarheadStatusResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<WarheadStatusResult>> WarheadsGetStatusAsyncWithHttpInfo ()
        {

            var localVarPath = "/api/warheads/status";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WarheadsGetStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<WarheadStatusResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (WarheadStatusResult) Configuration.ApiClient.Deserialize(localVarResponse, typeof(WarheadStatusResult)));
            
        }

        /// <summary>
        /// Launch the nuclear warheads. The launch code changes every day and is in the format YYMMDD-AAAAAAAAAA (where YYMMDD is 6 digits representing the current              date and AAAAAAAAAA is the pass phrase given to the President). May return an error if somethings are not quite right.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="launchCode">The launch code. See the implementation notes.</param>
        /// <returns>WarheadLaunchResult</returns>
        public WarheadLaunchResult WarheadsLaunch (string launchCode)
        {
             ApiResponse<WarheadLaunchResult> localVarResponse = WarheadsLaunchWithHttpInfo(launchCode);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Launch the nuclear warheads. The launch code changes every day and is in the format YYMMDD-AAAAAAAAAA (where YYMMDD is 6 digits representing the current              date and AAAAAAAAAA is the pass phrase given to the President). May return an error if somethings are not quite right.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="launchCode">The launch code. See the implementation notes.</param>
        /// <returns>ApiResponse of WarheadLaunchResult</returns>
        public ApiResponse< WarheadLaunchResult > WarheadsLaunchWithHttpInfo (string launchCode)
        {
            // verify the required parameter 'launchCode' is set
            if (launchCode == null)
                throw new ApiException(400, "Missing required parameter 'launchCode' when calling WarheadsApi->WarheadsLaunch");

            var localVarPath = "/api/warheads/launch";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (launchCode != null) localVarQueryParams.Add("launchCode", Configuration.ApiClient.ParameterToString(launchCode)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WarheadsLaunch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<WarheadLaunchResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (WarheadLaunchResult) Configuration.ApiClient.Deserialize(localVarResponse, typeof(WarheadLaunchResult)));
            
        }

        /// <summary>
        /// Launch the nuclear warheads. The launch code changes every day and is in the format YYMMDD-AAAAAAAAAA (where YYMMDD is 6 digits representing the current              date and AAAAAAAAAA is the pass phrase given to the President). May return an error if somethings are not quite right.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="launchCode">The launch code. See the implementation notes.</param>
        /// <returns>Task of WarheadLaunchResult</returns>
        public async System.Threading.Tasks.Task<WarheadLaunchResult> WarheadsLaunchAsync (string launchCode)
        {
             ApiResponse<WarheadLaunchResult> localVarResponse = await WarheadsLaunchAsyncWithHttpInfo(launchCode);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Launch the nuclear warheads. The launch code changes every day and is in the format YYMMDD-AAAAAAAAAA (where YYMMDD is 6 digits representing the current              date and AAAAAAAAAA is the pass phrase given to the President). May return an error if somethings are not quite right.
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="launchCode">The launch code. See the implementation notes.</param>
        /// <returns>Task of ApiResponse (WarheadLaunchResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<WarheadLaunchResult>> WarheadsLaunchAsyncWithHttpInfo (string launchCode)
        {
            // verify the required parameter 'launchCode' is set
            if (launchCode == null)
                throw new ApiException(400, "Missing required parameter 'launchCode' when calling WarheadsApi->WarheadsLaunch");

            var localVarPath = "/api/warheads/launch";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (launchCode != null) localVarQueryParams.Add("launchCode", Configuration.ApiClient.ParameterToString(launchCode)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WarheadsLaunch", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<WarheadLaunchResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (WarheadLaunchResult) Configuration.ApiClient.Deserialize(localVarResponse, typeof(WarheadLaunchResult)));
            
        }

    }
}
