/* 
 * Thermonuclear War REST API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WarheadsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class WarheadsApiTests
    {
        private WarheadsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new WarheadsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WarheadsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' WarheadsApi
            //Assert.IsInstanceOfType(typeof(WarheadsApi), instance, "instance is a WarheadsApi");
        }

        
        /// <summary>
        /// Test WarheadsGetStatus
        /// </summary>
        [Test]
        public void WarheadsGetStatusTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.WarheadsGetStatus();
            //Assert.IsInstanceOf<WarheadStatusResult> (response, "response is WarheadStatusResult");
        }
        
        /// <summary>
        /// Test WarheadsLaunch
        /// </summary>
        [Test]
        public void WarheadsLaunchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string launchCode = null;
            //var response = instance.WarheadsLaunch(launchCode);
            //Assert.IsInstanceOf<WarheadLaunchResult> (response, "response is WarheadLaunchResult");
        }
        
    }

}
